#include "liushuideng.h"
#include "bsp_systick.h"
#include "led.h"

void ximie(void)
{
	GPIO_SetBits(LED1_GPIO_PORT,LED1_GPIO_PIN);
	GPIO_SetBits(LED2_GPIO_PORT,LED2_GPIO_PIN);
	GPIO_SetBits(LED3_GPIO_PORT,LED3_GPIO_PIN);
	GPIO_SetBits(LED4_GPIO_PORT,LED4_GPIO_PIN);
	GPIO_SetBits(LED5_GPIO_PORT,LED5_GPIO_PIN);
	GPIO_SetBits(LED6_GPIO_PORT,LED6_GPIO_PIN);
	GPIO_SetBits(LED7_GPIO_PORT,LED7_GPIO_PIN);
	GPIO_SetBits(LED8_GPIO_PORT,LED8_GPIO_PIN);
}

void R_liushuideng(void)
{
		GPIO_ResetBits(LED1_GPIO_PORT,LED1_GPIO_PIN);
		SysTick_Delay_ms(50);
		GPIO_SetBits(LED1_GPIO_PORT,LED1_GPIO_PIN);
		
		GPIO_ResetBits(LED2_GPIO_PORT,LED2_GPIO_PIN);
		SysTick_Delay_ms(50);
		GPIO_SetBits(LED2_GPIO_PORT,LED2_GPIO_PIN);
		
		GPIO_ResetBits(LED3_GPIO_PORT,LED3_GPIO_PIN);
		SysTick_Delay_ms(50);
		GPIO_SetBits(LED3_GPIO_PORT,LED3_GPIO_PIN);
		
		GPIO_ResetBits(LED4_GPIO_PORT,LED4_GPIO_PIN);
		SysTick_Delay_ms(50);
		GPIO_SetBits(LED4_GPIO_PORT,LED4_GPIO_PIN);
		
		GPIO_ResetBits(LED5_GPIO_PORT,LED5_GPIO_PIN);
		SysTick_Delay_ms(50);
		GPIO_SetBits(LED5_GPIO_PORT,LED5_GPIO_PIN);
		
		GPIO_ResetBits(LED6_GPIO_PORT,LED6_GPIO_PIN);
		SysTick_Delay_ms(50);
		GPIO_SetBits(LED6_GPIO_PORT,LED6_GPIO_PIN);
		
		GPIO_ResetBits(LED7_GPIO_PORT,LED7_GPIO_PIN);
		SysTick_Delay_ms(50);
		GPIO_SetBits(LED7_GPIO_PORT,LED7_GPIO_PIN);
		
		GPIO_ResetBits(LED8_GPIO_PORT,LED8_GPIO_PIN);
		SysTick_Delay_ms(100);
		GPIO_SetBits(LED8_GPIO_PORT,LED8_GPIO_PIN);
}
void L_liushuideng(void)
{
		GPIO_ResetBits(LED8_GPIO_PORT,LED8_GPIO_PIN);
		SysTick_Delay_ms(50);
		GPIO_SetBits(LED8_GPIO_PORT,LED8_GPIO_PIN);
	
		GPIO_ResetBits(LED7_GPIO_PORT,LED7_GPIO_PIN);
		SysTick_Delay_ms(50);
		GPIO_SetBits(LED7_GPIO_PORT,LED7_GPIO_PIN);
	
		GPIO_ResetBits(LED6_GPIO_PORT,LED6_GPIO_PIN);
		SysTick_Delay_ms(50);
		GPIO_SetBits(LED6_GPIO_PORT,LED6_GPIO_PIN);

		GPIO_ResetBits(LED5_GPIO_PORT,LED5_GPIO_PIN);
		SysTick_Delay_ms(50);
		GPIO_SetBits(LED5_GPIO_PORT,LED5_GPIO_PIN);

		GPIO_ResetBits(LED4_GPIO_PORT,LED4_GPIO_PIN);
		SysTick_Delay_ms(50);
		GPIO_SetBits(LED4_GPIO_PORT,LED4_GPIO_PIN);	
	
		GPIO_ResetBits(LED3_GPIO_PORT,LED3_GPIO_PIN);
		SysTick_Delay_ms(50);
		GPIO_SetBits(LED3_GPIO_PORT,LED3_GPIO_PIN);

		GPIO_ResetBits(LED2_GPIO_PORT,LED2_GPIO_PIN);
		SysTick_Delay_ms(50);
		GPIO_SetBits(LED2_GPIO_PORT,LED2_GPIO_PIN);
		
				GPIO_ResetBits(LED1_GPIO_PORT,LED1_GPIO_PIN);
		SysTick_Delay_ms(50);
		GPIO_SetBits(LED1_GPIO_PORT,LED1_GPIO_PIN);
}

void dan_shan(void)
{
		GPIO_ResetBits(LED2_GPIO_PORT,LED2_GPIO_PIN);
		GPIO_ResetBits(LED4_GPIO_PORT,LED4_GPIO_PIN);
		GPIO_ResetBits(LED6_GPIO_PORT,LED6_GPIO_PIN);
		GPIO_ResetBits(LED8_GPIO_PORT,LED8_GPIO_PIN);
		SysTick_Delay_ms(50);
		GPIO_SetBits(LED1_GPIO_PORT,LED1_GPIO_PIN);
		GPIO_SetBits(LED3_GPIO_PORT,LED3_GPIO_PIN);
		GPIO_SetBits(LED5_GPIO_PORT,LED5_GPIO_PIN);
		GPIO_SetBits(LED7_GPIO_PORT,LED7_GPIO_PIN);
		SysTick_Delay_ms(50);
		GPIO_ResetBits(LED1_GPIO_PORT,LED1_GPIO_PIN);
		GPIO_ResetBits(LED3_GPIO_PORT,LED3_GPIO_PIN);
		GPIO_ResetBits(LED5_GPIO_PORT,LED5_GPIO_PIN);
		GPIO_ResetBits(LED7_GPIO_PORT,LED7_GPIO_PIN);
		SysTick_Delay_ms(50);	
		GPIO_SetBits(LED2_GPIO_PORT,LED2_GPIO_PIN);
		GPIO_SetBits(LED4_GPIO_PORT,LED4_GPIO_PIN);
		GPIO_SetBits(LED6_GPIO_PORT,LED6_GPIO_PIN);
		GPIO_SetBits(LED8_GPIO_PORT,LED8_GPIO_PIN);
		SysTick_Delay_ms(50);
}

